version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: h5py
    versions:
    - ">= 3.a, < 4"
  - dependency-name: numpy
    versions:
    - "> 1.18.5, < 2"
  - dependency-name: sphinx
    versions:
    - "> 3.5.3, < 3.6"
  - dependency-name: black
    versions:
    - 21.4b0
    - 21.4b1
  - dependency-name: pylint
    versions:
    - 2.7.3
  - dependency-name: pre-commit
    versions:
    - 2.11.0
    - 2.11.1
  - dependency-name: tensorboard-plugin-profile
    versions:
    - 2.4.0
  - dependency-name: sphinx
    versions:
    - 3.5.0
