dataset:
  train:
    dir:
      - demos/unpaired_us_prostate_cv/dataset/fold0
      - demos/unpaired_us_prostate_cv/dataset/fold1
      - demos/unpaired_us_prostate_cv/dataset/fold2
      - demos/unpaired_us_prostate_cv/dataset/fold3
      - demos/unpaired_us_prostate_cv/dataset/fold4
      - demos/unpaired_us_prostate_cv/dataset/fold5
      - demos/unpaired_us_prostate_cv/dataset/fold6
      - demos/unpaired_us_prostate_cv/dataset/fold7
    format: h5
    labeled: false
  valid:
    dir: demos/unpaired_us_prostate_cv/dataset/fold8
    format: h5
    labeled: false
  test:
    dir: demos/unpaired_us_prostate_cv/dataset/fold9
    format: h5
    labeled: false
  type: unpaired # paired / unpaired / grouped
  image_shape: [64, 100, 100]
train:
  # define neural network structure
  method: "ddf" # the registration method, value should be ddf / dvf / conditional
  backbone:
    name: "local" # value should be local / global / unet
    num_channel_initial: 32 # number of initial channel in local net, controls the size of the network
    extract_levels: [0, 1, 2, 3]

  # define the loss function for training
  loss:
    image:
      name: "ssd"
      weight: 1.0
    label:
      weight: 1.0
      name: "dice"
      scales: [0, 1, 2, 4, 8, 16]
    regularization:
      weight: 0.25 # weight of regularization loss
      name: "bending" # options include "bending", "gradient"

  # define the optimizer
  optimizer:
    name: "Adam"
    learning_rate: 1.0e-4

  # define the hyper-parameters for preprocessing
  preprocess:
    data_augmentation:
      name: "affine"
    batch_size: 4
    shuffle_buffer_num_batch: 1 # shuffle_buffer_size = batch_size * shuffle_buffer_num_batch

  # other training hyper-parameters
  epochs: 6000 # number of training epochs
  save_period: 1000 # the model will be saved every `save_period` epochs.
