dataset:
  dir:
    train: "demos/paired_mrus_brain/dataset/train"
    valid: "demos/paired_mrus_brain/dataset/test"
    test: "demos/paired_mrus_brain/dataset/test"
  format: "nifti"
  type: "paired" # paired / unpaired / grouped
  labeled: false
  moving_image_shape: [256, 256, 288]
  fixed_image_shape: [256, 256, 288]
train:
  method: "ddf" # the registration method, value should be ddf / dvf / conditional
  backbone:
    name: "local" # value should be local / global / unet
    num_channel_initial: 4 # number of initial channel in local net, controls the size of the network
    extract_levels: [0, 1, 2, 3]
  loss:
    image:
      name: "ssd"
      weight: 0.1
    label:
      weight: 1.0
      name: "dice"
      scales: [0, 1, 2, 4, 8, 16]
    regularization:
      weight: 0.25
      name: "bending"
  preprocess:
    data_augmentation:
      name: "affine"
    batch_size: 2
    shuffle_buffer_num_batch: 1
  optimizer:
    name: "Adam"
    learning_rate: 1.0e-4
  epochs: 2000
  save_period: 50
