dataset:
  dir:
    train: "demos/paired_ct_lung/dataset/train"
    valid: "demos/paired_ct_lung/dataset/valid"
    test: "demos/paired_ct_lung/dataset/test"
  format: "nifti"
  type: "paired" # paired / unpaired / grouped
  labeled: true
  moving_image_shape: [96, 96, 104]
  fixed_image_shape: [96, 96, 104]
train:
  method: "ddf" # the registration method, value should be ddf / dvf / conditional
  backbone:
    name: "global" # value should be local / global / unet
    num_channel_initial: 32 # number of initial channel in local net, controls the size of the network
  loss:
    image:
      name: "ssd"
      weight: 1.0
    label:
      weight: 1.0
      name: "dice"
      scales: [0, 1, 2, 4, 8, 16]
  preprocess:
    batch_size: 4
    shuffle_buffer_num_batch: 1
  optimizer:
    name: "adam"
    adam:
      learning_rate: 1.0e-6
  epochs: 8000
  save_period: 1000
