# TODO to update
data:
  dir: "data/test/nifti/demo" # required
  type: "nifti"
  moving_image_shape: [64, 64, 60]
  fixed_image_shape: [44, 59, 41]
  sample_label:
    train: "sample" # sample or first or all
    test: "first"

tf:
  model:
    method: "conditional" # ddf or conditional or seg
    backbone:
      name: "local"
      out_kernel_initializer: "glorot_uniform" # zeros or glorot_uniform
      out_activation: "sigmoid"
    local:
      num_channel_initial: 2
      extract_levels: [0, 1, 2, 3, 4]
    unet:
      num_channel_initial: 4
      depth: 2
      pooling: true
      concat_skip: false
  loss:
    similarity:
      image:
        name: "lncc"
        weight: 0.
      label:
        weight: 1.0
        name: "single_scale"
        multi_scale:
          loss_type: "dice"
          loss_scales: [0, 1, 2, 4, 8, 16, 32]
        single_scale:
          loss_type: "cross-entropy"
    regularization:
      weight: 0.5
      energy_type: "bending"
  data:
    batch_size: 2
    shuffle_buffer_num_batch: 0
  opt:
    name: "adam"
    adam:
      learning_rate: 1.0e-5
    sgd:
      learning_rate: 1.0e-4
      momentum: 0.9
    rms:
      learning_rate: 1.0e-4
      momentum: 0.9
  epochs: 6
  save_period: 2
  histogram_freq: 2
