dataset:
  dir:
    train: "demos/unpaired_ct_abdomen/dataset/train"
    valid: "demos/unpaired_ct_abdomen/dataset/val"
    test: "demos/unpaired_ct_abdomen/dataset/test"
  format: "nifti"
  type: "unpaired" # paired / unpaired / grouped
  labeled: false
  image_shape: [77, 64, 102] # original [192,160,256]

train:
  model:
    method: "ddf" # ddf / dvf / conditional
    backbone: "unet"
    local:
      num_channel_initial: 16
      extract_levels: [0, 1, 2, 3, 4]
    unet:
      num_channel_initial: 16
      depth: 3
      pooling: true
      concat_skip: true
  loss:
    dissimilarity:
      image:
        name: "ssd"
        weight: 1
      label:
        weight: 0
        name: "multi_scale"
        multi_scale:
          loss_type: "dice"
          loss_scales: [0, 1, 2, 4, 8, 16]
    regularization:
      weight: 0.1
      energy_type: "gradient-l2"
  preprocess:
    batch_size: 4
    shuffle_buffer_num_batch: 1
  optimizer:
    name: "adam"
    adam:
      learning_rate: 1.0e-4
  epochs: 5000
  save_period: 250
